services:
  - type: web
    name: discord-bot-dashboard
    env: python
    buildCommand: pip install -r minimal_requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: discord-bot-db
          property: connectionString
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
databases:
  - name: discord-bot-db
    plan: free