services:
  - type: web
    name: discord-bot-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_web_only.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: discord-bot-db
          property: connectionString
databases:
  - name: discord-bot-db
    plan: free